### PR TITLE
gyro: lua configurable global gyro rates and gains

### PR DESCRIPTION
**Pull request by bd4**

### CODE REVIEW

**Comment by bd4** [comment]
Compiles. Not fully tested yet - having trouble getting my SuperP to bind, wondering if it is getting hung up in gyro init. It does enter WIFI mode and I've configured pins 19/22 for scl/sda in hardware.html, as recommended in the manual. I did have it binding in stable firmware.

**Comment by bd4** [comment]
Finally got it to bind, the nested menus for Gyro Gains->{} Axis are not working yet.

**Comment by bd4** [comment]
Fixed, had to use separate items for each subfolder even though configuration was the same.

**Comment by awigen** [comment]
That's great, a good step forward!

**Pull request merged**
